# Generated by Django 4.2.7 on 2023-11-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='first_name',
            field=models.CharField(default='Default', max_length=100, verbose_name='First Name!'),
        ),
    ]
