# Generated by Django 4.2.7 on 2023-11-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_survey_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='first_name',
            field=models.CharField(default='Default', max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=100),
        ),
    ]
