# Generated by Django 4.2.7 on 2023-11-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_survey_status_alter_survey_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='directory_url',
            field=models.CharField(default='default', max_length=200, verbose_name='University Profile or Directory URL (this will be included in theaffiliated faculty directory in lieu of other contact information)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='ds_class_1',
            field=models.CharField(default='default', max_length=100, verbose_name='Class 1'),
        ),
        migrations.AddField(
            model_name='survey',
            name='ds_class_2',
            field=models.CharField(default='default', max_length=100, verbose_name='Class 2'),
        ),
        migrations.AddField(
            model_name='survey',
            name='ds_class_3',
            field=models.CharField(default='default', max_length=100, verbose_name='Class 3'),
        ),
        migrations.AddField(
            model_name='survey',
            name='google_url',
            field=models.CharField(default='default', max_length=100, verbose_name='Semantic url(https://scholar.google.com)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='research_count',
            field=models.IntegerField(default=0, verbose_name='How many data science related research projects do you expect to work on in 2020 as PI, co-PI, or significant contributor?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='research_desc',
            field=models.TextField(default='default', max_length=150, verbose_name='Research Description (Provide a 75-150 word general description about your research emphasizing the data science tools and methodologies you use.)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='research_examples',
            field=models.TextField(default='Default', max_length=200, verbose_name='List titles of one to three recent data science related research projects that you feel highlight your work. Feel free to include citation links, if desired.'),
        ),
        migrations.AddField(
            model_name='survey',
            name='research_tagline',
            field=models.CharField(default='default', max_length=100, verbose_name='Research Tagline (Use 10 words or less to describe your research. This will be the tagline on in the affiliated faculty web-site and directory listing.)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='school',
            field=models.CharField(default='default', max_length=200, verbose_name='School and/or Department (e.g. ABC College of Business, Department of Marketing)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='semantic_url',
            field=models.CharField(default='default', max_length=100, verbose_name='Semantic url(https://www.semanticscholar.org/faq)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='title',
            field=models.CharField(default='default', max_length=200, verbose_name='Title (as used for university related business)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='university',
            field=models.CharField(choices=[('Marquette University', 'Marquette University'), ('University of Wisconsin - Milwaukee', 'University of Wisconsin - Milwaukee'), ('Other', 'Other')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='survey',
            name='university_desc',
            field=models.CharField(default='default', max_length=300, verbose_name='If you selected other, please let us know your University or Company affiliation.'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Visiting - 2+ years at MU or UWM', 'Visiting - 2+ years at MU or UWM'), ('Adjunct Faculty - 2+ years at MU or UWM', 'Adjunct Faculty - 2+ years at MU or UWM'), ('Visiting Faculty - Less than 2 years at MU or UWM', 'Visiting Faculty - Less than 2 years at MU or UWM'), ('Adjunct Faculty - Less than 2 years at MU or UWM', 'Adjunct Faculty - Less than 2 years at MU or UWM'), ('Faculty at other university', 'Faculty at other university'), ('Non-faculty/Industry representative', 'Non-faculty/Industry representative')], max_length=100, verbose_name='What is your status at the Marquette or UW-Milwaukee?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status_desc',
            field=models.TextField(default='Default', max_length=500, verbose_name='If visiting faculty, add years at this universtity/name of home university For adjunct, add years serving as an adjunct for this university and place of regular employment. For other, describe your role.'),
        ),
    ]
