# Generated by Django 4.2.7 on 2023-11-20 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0005_survey_directory_url_survey_ds_class_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
