# Generated by Django 4.2.7 on 2023-11-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_alter_survey_ds_techniques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='ds_techniques',
            field=models.CharField(default='', max_length=600),
        ),
    ]
