# Generated by Django 4.2.7 on 2023-11-22 20:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_alter_survey_ds_techniques'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='application_domains_1',
            field=models.CharField(default='default', max_length=150, verbose_name='Application 1'),
        ),
        migrations.AddField(
            model_name='survey',
            name='application_domains_2',
            field=models.CharField(default='default', max_length=150, verbose_name='Application 2'),
        ),
        migrations.AddField(
            model_name='survey',
            name='application_domains_3',
            field=models.CharField(default='default', max_length=150, verbose_name='Application 3'),
        ),
        migrations.AddField(
            model_name='survey',
            name='application_domains_4',
            field=models.CharField(default='default', max_length=150, verbose_name='Application 4'),
        ),
        migrations.AddField(
            model_name='survey',
            name='application_domains_5',
            field=models.CharField(default='default', max_length=150, verbose_name='Application 5'),
        ),
        migrations.AddField(
            model_name='survey',
            name='conclusion',
            field=models.TextField(default='default', max_length=300, verbose_name='Describe how your affiliation will support the institute in the next year (e.g. volunteer for events, present research at NMDSI event, conduct workshop for NMDSI, teach data science classes, conduct and publish data science research, etc.)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='contact_list',
            field=models.CharField(choices=[('Yes, put me on the list', 'Yes, put me on the list'), ('No, not interested at this time', 'No, not interested at this time'), ("Possibly, let's chat when the time is right", "Possibly, let's chat when the time is right")], default='', max_length=150, verbose_name='We are building a list of potential articles, blog posts, and podcasts highlighting the work of affiliated faculty. Would you like to be added to that list? (Note: No publication schedule has been determined.)'),
        ),
        migrations.AddField(
            model_name='survey',
            name='ds_techniques_other',
            field=models.TextField(default='default', max_length=300, verbose_name='Other primary data science methods or techniques not listed above.'),
        ),
        migrations.AddField(
            model_name='survey',
            name='thank_you',
            field=models.TextField(default='default', max_length=300, verbose_name='Thank you for submitting your request to be affiliated with the Northwestern Mutual Data Science Institute. Your request will be reviewed by the program administrator within two weeks. Your email address will be added to the NMDSI affiliated faculty list and your profile added to a future version of the NMDSI web-site. Please share any questions or comments you have in the space below then click submit to close the survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='ds_techniques',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Algorithms', 'Algorithms'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Bayesian Methods', 'Bayesian Methods'), ('Causal Inference', 'Causal Inference'), ('Classification', 'Classification'), ('Computational Tools for Data Science', 'Computational Tools for Data Science'), ('Data Collection Design', 'Data Collection Design'), ('Data Management', 'Data Management'), ('Data Mining', 'Data Mining'), ('Data Munging', 'Data Munging'), ('Data Quality', 'Data Quality'), ('Data Security and Privacy', 'Data Security and Privacy'), ('Data Visualization', 'Data Visualization'), ('Database Systems and Infrastructure', 'Database Systems and Infrastructure'), ('Decision Science', 'Decision Science'), ('Deep Learning', 'Deep Learning'), ('Digital Data Curation', 'Digital Data Curation'), ('Dynamical Models', 'Dynamical Models'), ('Econometrics', 'Econometrics'), ('Geographic Information Systems', 'Geographic Information Systems'), ('Graph Theory and Graph-based Methods', 'Graph Theory and Graph-based Methods'), ('Heterogeneous Data Integration', 'Heterogeneous Data Integration'), ('High-Dimensional Data Analysis', 'High-Dimensional Data Analysis'), ('Human-Computer Interaction', 'Human-Computer Interaction'), ('Image Data Processing and Analysis', 'Image Data Processing and Analysis'), ('Information Theory', 'Information Theory'), ('Longitudinal Data Analysis', 'Longitudinal Data Analysis'), ('Machine Learning', 'Machine Learning'), ('Mathematics', 'Mathematics'), ('Missing Data and Imputation', 'Missing Data and Imputation'), ('Natural Language Processing', 'Natural Language Processing'), ('Network Analysis', 'Network Analysis'), ('Number Theory', 'Number Theory'), ('Ontology', 'Ontology'), ('Optimization', 'Optimization'), ('Pattern Analysis and Classification', 'Pattern Analysis and Classification'), ('Predictive Modeling', 'Predictive Modeling'), ('Psychometrics', 'Psychometrics'), ('Real-time Data Processing', 'Real-time Data Processing'), ('Signal Processing', 'Signal Processing'), ('Sparse Data Analysis', 'Sparse Data Analysis'), ('Spatio-Temporal Data Analysis', 'Spatio-Temporal Data Analysis'), ('Statistical Interference', 'Statistical Interference'), ('Statistical Modeling', 'Statistical Modeling'), ('Statistics', 'Statistics'), ('Survey Methodology', 'Survey Methodology'), ('Tensor Analysis', 'Tensor Analysis'), ('Time Series Analysis', 'Time Series Analysis'), ('Other', 'Other')], max_length=600, verbose_name="Data Science Methods and Analytical Techniques (Pick the most prevalent methodology or techniques you teach or use in your data science research. Select 'Other' to list others you frequently use in the comment box. This will become a filterable list on a future version of the faculty web-site. Limit to 5-7.)"),
        ),
    ]
