# Generated by Django 4.2.7 on 2023-11-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_survey_application_domains_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='directory_url',
            field=models.CharField(default='default', max_length=200, verbose_name='University Profile or Directory URL'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='ds_techniques_other',
            field=models.TextField(default='default', max_length=200, verbose_name='Other primary data science methods or techniques not listed above.'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='email',
            field=models.EmailField(default='Default@default.com', max_length=254, verbose_name='University Email address:'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='first_name',
            field=models.CharField(default='Default', max_length=100, verbose_name='First Name:'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Visiting - 2+ years at MU or UWM', 'Visiting - 2+ years at MU or UWM'), ('Adjunct Faculty - 2+ years at MU or UWM', 'Adjunct Faculty - 2+ years at MU or UWM'), ('Visiting Faculty - Less than 2 years at MU or UWM', 'Visiting Faculty - Less than 2 years at MU or UWM'), ('Adjunct Faculty - Less than 2 years at MU or UWM', 'Adjunct Faculty - Less than 2 years at MU or UWM'), ('Faculty at other university', 'Faculty at other university'), ('Non-faculty/Industry representative', 'Non-faculty/Industry representative')], default='', max_length=100, verbose_name='What is your status at the Marquette or UW-Milwaukee?'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='suffix',
            field=models.CharField(default='Default', max_length=100, verbose_name='Suffix + Full Name:'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='thank_you',
            field=models.TextField(blank=True, default='default', max_length=300, verbose_name='Thank you for submitting your request to be affiliated with the Northwestern Mutual Data Science Institute. Your request will be reviewed by the program administrator within two weeks. Your email address will be added to the NMDSI affiliated faculty list and your profile added to a future version of the NMDSI web-site. Please share any questions or comments you have in the space below then click submit to close the survey'),
        ),
    ]
